# Generated by Django 5.0 on 2024-01-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_after_transaction',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=12),
            preserve_default=False,
        ),
    ]
